language: php

php:
  - '5.6'
  - hhvm
  - nightly

before_script:
  - composer install --dev --no-interaction


script:
  - mkdir -p build/logs
  - vendor/bin/phpunit --bootstrap src/Sum.php Tests/SumTest.php
after_script:
  - "curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.1.1)' https://codeclimate.com/test_reports"